### ISSUE TITLE
RSS does not show in Chrome 67 preview

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-rss#107]
Preview: http://preview.risevision.com/?type=presentation&id=f9b8c29b-8498-49a7-aa7f-89ac20008884

What you should see: https://www.screencast.com/t/HNIvuUlc and what you do see in other chrome versions

**Comment by stulees** [comment]
The fix has been deployed.

---

**Problem** 

- Widgets stopped displaying content on Chrome 67 in Preview. Specifically, widgets that import one of our Polymer web components (ie. rise-rss).
- They displayed content correctly running locally via localhost in Chrome 67. 
- Further investigation revealed the _WebComponentsReady_ event was not firing from the `webcomponents-lite.js` from the `webcomponentsjs` polyfill dependency

**Solution** 

- Upgraded to latest version of `webcomponentsjs` used for the polyfill of web components and used `webcomponents-loader.js` instead of deprecated `webcomponents-lite.js`. This allowed to no longer have to listen for _WebComponentsReady_ function as -loader.js sychronously injects required polyfills based on browser features. 
- An additional problem and solution was required for Spreadsheet Widget as that widget is different (React and webpack build), see https://github.com/Rise-Vision/widget-google-spreadsheet/pull/297

**How to validate** 

1. Build a presentation to use one of or all of the following Widgets: Image, Video, RSS, Spreadsheet
2. Test on Preview
