### ISSUE TITLE
If the Feed parser cannot access the RSS feed, no error is reported in the Widget settings

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#123]
### What is the expected behavior?
If the feed cannot be accessed or displayed, the error should be displayed in the Widget Settings.

### What is the actual behavior?
Nothing appears in the Widget settings to indicate why the RSS feed will not show, and nothing shows in the Presentation

### What steps can be taken to replicate the problem?
1. Add either of the following feeds to a Presentation with the RSS Widget:
- http://tenants.brisbanemarkets.com.au/category/market-bulletins/feed/
- http://news.brisbanemarkets.com.au/feed/
2. Notice that no errors show in the Widget Settings.
3. Save and Preview the Presentation, notice that nothing shows in the Presentation.

The feeds both validate, but cannot be accessed by the parser:
![2018-08-08_11-24-16](https://user-images.githubusercontent.com/6862256/43847011-a3365792-9afd-11e8-8ffc-5710d9359b79.png)

Since the feed is valid, it may be worthwhile to have the error show that our Feed Parser cannot access the feed, or something similar, so the user knows what to do to correct.

**Comment by stulees** [comment]
The general reason why a 403 forbidden error can be returned when making a request via a feed parser is because the server of the feed requires `user-agent` and/or `accept headers`. This is common and we have always ensured we do this in our feed-parser, see [here](https://github.com/Rise-Vision/feed-parser/blob/5159d26043939574b4220fa52aa944be03d2d8f7/app/parser.js#L20-L22)

The 403 error is reported in very low numbers. It is not clear as to what the server of these feeds requires beyond the request headers already being set by our feed-parser. 

To help direct the user to an action to take, we have handled a 403 specifically and now display the following message on screen:

> Sorry, there was a problem requesting the RSS feed, please contact the owner of the RSS feed to resolve.

Closing the issue.  @robb-price FYI
