### ISSUE TITLE
RSS Widget not displaying full feed

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-rss#126]
**What is the expected behavior?**

The RSS widget should display all of the items from the RSS feed.

**What is the actual behavior?**

The RSS widget doesn't display all of the data from certain RSS feeds such as this one: https://lcu.edu/tvs/php/menu.php?period=Lunch

**Steps to reproduce:** 

1. Add the above RSS feed to an RSS widget and Save + Publish the presentation.
2. Preview or schedule the Presentation to a Display and you'll see that not all of the data from the feed is showing.

**Comment by stulees** [comment]
The RSS widget has a limitation of 120 characters per each item to display from a feed. The Widget truncates the description with an ellipsis in the case of item description exceeding the limit.

We can't fix this as it is a limitation of the RSS widget in order to adhere to different layouts. Closing the issue. @kaden-rise @btfrise FYI
